name: Update Master Branch

on:
  push:
    branches:
      - master

jobs:
  update-master:
    runs-on: ubuntu-latest
    needs: validate-pr

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. Grant execute permission to gradlew
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      # 4. Extract version
      - name: Extract versionName
        id: extract_version
        run: |
          VERSION_NAME=$(./gradlew -q printVersionName)
          echo "Extracted VERSION_NAME=$VERSION_NAME"
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      # 5. Update README.md and remove _Beta
      - name: Update README.md
        run: |
          sed -i "s|\\[VERSION\\](.*)|[VERSION](https://img.shields.io/badge/Version-${VERSION_NAME}-blue)|" README.md
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update README.md to official release $VERSION_NAME" || echo "No changes to commit"
          git push || echo "Nothing to push"

      # 6. Create Release Tag
      - name: Create Release Tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          TAG_NAME="v${VERSION_NAME}"
          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
              echo "Tag $TAG_NAME already exists. Skipping tag creation."
          else
              git tag -a "$TAG_NAME" -m "Official release $TAG_NAME"
              git push origin "$TAG_NAME"
          fi

      # 7. Create GitHub Release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: "v$VERSION_NAME"
          release_name: "Release v$VERSION_NAME"
          body: |
            ## What's New
            - Updated version to $VERSION_NAME
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
