name: Update README with Version

on:
  push:
    branches:
      - master
      - develop

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Java's configuration to read Gradle
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      # 3. Grant execute permission to gradlew
      # This ensures that the gradlew file can be executed without permission issues
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      # 4. Extract versionName from build.gradle
      # This runs a custom Gradle task to extract the dynamically generated versionName
      - name: Extract versionName
        id: extract_version
        run: |
          VERSION_NAME=$(./gradlew -q printVersionName)
          echo "Extracted VERSION_NAME=$VERSION_NAME"
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      # 5. Update README.md with the extracted version
      # Replace the placeholder in README.md with the current versionName
      - name: Update README.md with version
        run: |
          sed -i "s|\\[VERSION\\](.*)|[VERSION](https://img.shields.io/badge/Version-$VERSION_NAME-blue)|" README.md
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update README.md with version $VERSION_NAME"
          git push

      # 6. Create Git Tag
      # Create and push a Git tag depending on the branch (beta for develop, stable for master)
      - name: Create Git Tag
        if: success()
        run: |
          if [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            git tag -a "v$VERSION_NAME-beta" -m "Beta release version $VERSION_NAME"
            git push origin "v$VERSION_NAME-beta"
          else
            git tag -a "v$VERSION_NAME" -m "Release version $VERSION_NAME"
            git push origin "v$VERSION_NAME"
          fi
