name: Update Develop Branch

on:
  push:
    branches:
      - develop

jobs:
  update-develop:
    runs-on: ubuntu-latest
    needs: validate-pr

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. Grant execute permission to gradlew
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      # 4. Increment version and extract it
      - name: Extract and increment version
        id: extract_version
        run: |
          VERSION_NAME=$(./gradlew -q printVersionName)
          echo "Extracted VERSION_NAME=$VERSION_NAME"
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      # 5. Create Beta Tag
      - name: Create Beta Tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          TAG_NAME="v${VERSION_NAME}_Beta"
          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
              echo "Tag $TAG_NAME already exists. Skipping tag creation."
          else
              git tag -a "$TAG_NAME" -m "Beta release $TAG_NAME"
              git push origin "$TAG_NAME"
          fi

      # 6. Update README.md
      - name: Update README.md
        run: |
          sed -i "s|\\[VERSION\\](.*)|[VERSION](https://img.shields.io/badge/Version-${VERSION_NAME}_Beta-blue)|" README.md
          sed -i "s|\\[VERSION\\](.*)|[VERSION](https://img.shields.io/badge/Version-${VERSION_NAME}_Beta-blue)|" README.md
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update README.md with version $VERSION_NAME" || echo "No changes to commit"
          git push || echo "Nothing to push"
