name: Update README with Version

on:
  push:
    branches:
      - master  # Run the action on the master branch
      - develop  # Run the action on the develop branch

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Java's configuration to read gradle
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      # 3. Extract versionName from build.gradle
      - name: Extract versionName
        id: extract_version
        run: |
          VERSION_NAME=$(grep versionName app/build.gradle | awk -F'"' '{print $2}')
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      # 4. Update README.md
      - name: Update README.md with version
        run: |
          sed -i "s/\\[VERSION\\](.*)/[VERSION](https:\/\/img.shields.io\/badge\/Version-$VERSION_NAME-blue)/" README.md
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update README.md with version $VERSION_NAME"
          git push

      # 5. Create Git Tag
      - name: Create Git Tag
        if: success()
        run: |
          if [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            git tag -a "v$VERSION_NAME-beta" -m "Beta release version $VERSION_NAME"
            git push origin "v$VERSION_NAME-beta"
          else
            git tag -a "v$VERSION_NAME" -m "Release version $VERSION_NAME"
            git push origin "v$VERSION_NAME"
          fi