name: Validate Pull Request

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. Grant execute permission to gradlew
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      # 4. Run Gradle Build
      - name: Run Gradle build
        run: ./gradlew clean build --debug --stacktrace

      # 5. Run Unit Tests
      - name: Run tests
        run: ./gradlew test

      # 6. Run Lint Check
      - name: Run Lint
        run: ./gradlew lint

      # 7. Update Status Badge in README
      - name: Update Status Badge
        if: always()
        run: |
          BADGE_STATUS=""
          BADGE_COLOR=""
          if [ "${{ job.status }}" == "success" ]; then
              BADGE_STATUS="working"
              BADGE_COLOR="green"
          else
              BADGE_STATUS="failing"
              BADGE_COLOR="red"
          fi
          sed -i "s|![STATUS](https://img.shields.io/badge/Status.*)|![STATUS](https://img.shields.io/badge/Status-${BADGE_STATUS}-${BADGE_COLOR})|" README.md
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update status badge to $BADGE_STATUS" || echo "No changes to commit"
          git push || echo "Nothing to push"
