name: Validate Pull Request

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - develop

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. Grant execute permission to gradlew
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      # 4. Run Gradle Build
      - name: Run Gradle build
        run: ./gradlew clean build --debug --stacktrace

      # 5. Run Unit Tests
      - name: Run tests
        run: ./gradlew test

      # 6. Run Lint Check
      - name: Run Lint
        run: ./gradlew lint

      # 7. Create Status Check for Success or Failure
      - name: Create Status Check
        if: always()
        run: |
          STATUS="failure"
          if [ "${{ job.status }}" == "success" ]; then
            STATUS="success"
          fi

          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d "{\"state\": \"$STATUS\", \"description\": \"Validation Workflow\", \"context\